version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - backend
  mongo:
    image: mongo:latest
    networks:
      - backend
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis
    restart: on-failure
    networks:
      - backend


networks:
  backend: