version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - backend
  mongo:
    image: mongo:latest
    networks:
      - backend
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis
    restart: on-failure
    networks:
      - backend


networks:
  backend: